[project]
name = "gen-events-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.4",
    "numpy>=2.4.2",
    "polars>=1.37.1",
    "pyarrow>=23.0.0",
]
