[project]
name = "duckdb-ndjson-at-scale"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "orjson>=3.11.5",
    "psutil>=7.2.2",
]
